version: 2
registries:
  cargo-example:
    type: cargo-registry
    registry: "thavaahariharan-test"
    url: https://jfrogghdemo.jfrog.io/artifactory/api/cargo/dependabot-cargo/index/
    token: "${{secrets.CARGO_TOKEN}}"
    
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    registries: 
      - cargo-example
    schedule:
      interval: "daily"
    groups:
      artifactory-dependency-group:
        patterns:
          - "*" # Soon, we'll use "delta_*"
          
