version: 2
registries:
  cargo-example:
    type: cargo-registry
    registry: "thavaahariharan-test"
    url: https://jfrogghdemo.jfrog.io/artifactory/api/cargo/dependabot-cargo/index/
    token: "Token ${{secrets.CARGO_TOKEN}}"
    
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    registries: 
      - cargo-example
    schedule:
      interval: "weekly"
